// Generated by tools/contracts/generate_models.py; do not edit by hand.
export const CATALOG_VERSION = "1.0" as const;
export const CATALOG_DIGEST = "90a642d6906b48fd75da620edb26625164f5b9192b88422c4b94dfad88a6beeb" as const;
export const MAX_JSON_ENVELOPE_BYTES = 1048576 as const;
export const HINA_CONTRACT_ECHO_V1 = "hina.contract.echo.v1" as const;
export type EventType = "hina.contract.echo.v1";
export const EVENT_TYPES = ["hina.contract.echo.v1"] as const;
export const EVENT_SCHEMA_FILES = {
  "hina.contract.echo.v1": "schemas/v1/events/hina.contract.echo.v1.schema.json"
} as const;

export interface MediaReference {
  mediaId: string;
  kind: "audio" | "binary" | "image" | "video";
  mimeType: string;
  byteLength: number;
  sha256: string;
  transportCorrelationId: string;
}

export interface HinaContractEchoV1Payload {
  message: string;
  locale: string;
  tags: string[];
  metadata: Record<string, boolean | number | string | null>;
}

export interface EventEnvelopeV1 {
  schemaVersion: "1.0";
  eventId: string;
  type: EventType;
  scope: "global" | "session" | "turn";
  sessionId: string | null;
  turnId: string | null;
  correlationId: string;
  causationId: string | null;
  source: string;
  trustLevel: "authenticated" | "owner" | "public" | "trusted_local" | "untrusted";
  occurredAt: string;
  expiresAt: string | null;
  deadline: string | null;
  idempotencyKey: string | null;
  streamId: string | null;
  sequence: number | null;
  media: MediaReference[];
  payload: HinaContractEchoV1Payload;
}

export interface HinaContractEchoV1Envelope extends EventEnvelopeV1 {
  type: "hina.contract.echo.v1";
  payload: HinaContractEchoV1Payload;
}
