// Generated by tools/contracts/generate_models.py; do not edit by hand.
import eventEnvelopeSchema from "../schemas/v1/event-envelope.schema.json";
import mediaReferenceSchema from "../schemas/v1/media-reference.schema.json";
import payloadSchemaHinaContractEchoV1 from "../schemas/v1/payloads/hina.contract.echo.v1.payload.schema.json";
import eventSchemaHinaContractEchoV1 from "../schemas/v1/events/hina.contract.echo.v1.schema.json";

export const CATALOG_VERSION = "1.0" as const;
export const CATALOG_DIGEST = "2aa4b921baad82e292d4d9e42c3e5d2dc42c84ffcd9c9b55f6dbaf0fb6a6ffdf" as const;
export const MAX_JSON_ENVELOPE_BYTES = 1048576 as const;
export const MAX_JSON_NESTING_DEPTH = 128 as const;
export const HINA_CONTRACT_ECHO_V1 = "hina.contract.echo.v1" as const;
export type EventType = "hina.contract.echo.v1";
export const EVENT_TYPES = ["hina.contract.echo.v1"] as const;
export const EVENT_SCHEMA_FILES = {
  "hina.contract.echo.v1": "schemas/v1/events/hina.contract.echo.v1.schema.json"
} as const;
export const EVENT_PAYLOAD_SCHEMA_FILES = {
  "hina.contract.echo.v1": "schemas/v1/payloads/hina.contract.echo.v1.payload.schema.json"
} as const;
export const SUPPORT_SCHEMA_MODULES = [
  eventEnvelopeSchema,
  mediaReferenceSchema,
  payloadSchemaHinaContractEchoV1,
] as const;
export const EVENT_SCHEMA_MODULES = {
  "hina.contract.echo.v1": eventSchemaHinaContractEchoV1,
} as const;

export interface MediaReference {
  byteLength: number;
  kind: "audio" | "binary" | "image" | "video";
  mediaId: string;
  mimeType: string;
  sha256: string;
  transportCorrelationId: string;
}

export interface HinaContractEchoV1Payload {
  locale: string;
  message: string;
  metadata: Record<string, boolean | number | null | string>;
  tags: string[];
}

export interface EventEnvelopeV1 {
  causationId: string | null;
  correlationId: string;
  deadline: string | null;
  eventId: string;
  expiresAt: string | null;
  idempotencyKey: string | null;
  media: MediaReference[];
  occurredAt: string;
  payload: HinaContractEchoV1Payload;
  schemaVersion: "1.0";
  scope: "global" | "session" | "turn";
  sequence: number | null;
  sessionId: string | null;
  source: string;
  streamId: string | null;
  trustLevel: "authenticated" | "owner" | "public" | "trusted_local" | "untrusted";
  turnId: string | null;
  type: EventType;
}

export interface HinaContractEchoV1Envelope extends EventEnvelopeV1 {
  type: "hina.contract.echo.v1";
  payload: HinaContractEchoV1Payload;
}

export type KnownEventEnvelopeV1 = HinaContractEchoV1Envelope;
