from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator


MAX_JSON_ENVELOPE_BYTES = 1_048_576
MAX_JSON_NESTING_DEPTH = 128
HEADER = "Generated by tools/contracts/generate_models.py; do not edit by hand."


@dataclass(frozen=True)
class EventProjection:
    name: str
    const_name: str
    envelope_type: str
    payload_type: str
    event_schema: dict[str, Any]
    event_schema_path: str
    payload_schema: dict[str, Any]
    payload_schema_path: str

    @property
    def payload_import_name(self) -> str:
        return camel_name("payloadSchema", self.name)

    @property
    def event_import_name(self) -> str:
        return camel_name("eventSchema", self.name)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    parser.add_argument("--root", default=".", help="repository root")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    try:
        rendered = render_outputs(root)
    except ValueError as exc:
        print(f"E_SCHEMA_WRONG_TYPE {exc}", file=sys.stderr)
        return 1

    changed: list[str] = []
    for relative, content in rendered.items():
        path = root / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            changed.append(relative)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if changed and args.check:
        for relative in changed:
            print(f"E_GEN_DRIFT {relative}", file=sys.stderr)
        return 1
    return 0


def render_outputs(root: Path) -> dict[str, str]:
    contracts = root / "packages" / "contracts"
    catalog = load_json(contracts / "catalog.v1.json")
    policy = load_json(contracts / "compatibility-policy.v1.json")
    events = validate_and_project_catalog(contracts, catalog)
    digest = digest_inputs(contracts)
    schema_files = {event.name: event.event_schema_path for event in events}
    payload_schema_files = {event.name: event.payload_schema_path for event in events}
    media_schema = load_json(contracts / "schemas/v1/media-reference.schema.json")
    envelope_schema = load_json(contracts / "schemas/v1/event-envelope.schema.json")
    return {
        "packages/contracts/src/hina_contracts/generated.py": render_python(
            catalog,
            digest,
            events,
            schema_files,
            payload_schema_files,
            media_schema,
            envelope_schema,
        ),
        "packages/contracts/src/generated.ts": render_typescript(
            catalog,
            digest,
            events,
            schema_files,
            payload_schema_files,
            media_schema,
            envelope_schema,
        ),
    }


def validate_and_project_catalog(contracts: Path, catalog: dict[str, Any]) -> list[EventProjection]:
    catalog_schema = load_json(contracts / "schemas/v1/catalog.schema.json")
    Draft202012Validator.check_schema(catalog_schema)
    Draft202012Validator(catalog_schema).validate(catalog)

    seen_names: set[str] = set()
    events: list[EventProjection] = []
    for event in sorted(catalog["events"], key=lambda item: item["name"]):
        name = event["name"]
        if name in seen_names:
            raise ValueError(f"duplicate catalog event name: {name}")
        seen_names.add(name)

        event_schema_path = event["schema"]
        event_schema_file = contracts / event_schema_path
        if not event_schema_file.is_file():
            raise ValueError(f"registered event schema does not exist: {event_schema_path}")
        event_schema = load_json(event_schema_file)
        Draft202012Validator.check_schema(event_schema)
        payload_schema_path = payload_ref_from_event_schema(event_schema, name)
        payload_schema_file = contracts / payload_schema_path
        if not payload_schema_file.is_file():
            raise ValueError(f"registered payload schema does not exist: {payload_schema_path}")
        payload_schema = load_json(payload_schema_file)
        Draft202012Validator.check_schema(payload_schema)
        events.append(
            EventProjection(
                name=name,
                const_name=constant_name(name),
                envelope_type=str(event_schema.get("title") or f"{pascal_name(name)}Envelope"),
                payload_type=str(payload_schema.get("title") or f"{pascal_name(name)}Payload"),
                event_schema=event_schema,
                event_schema_path=event_schema_path,
                payload_schema=payload_schema,
                payload_schema_path=payload_schema_path,
            )
        )
    return events


def payload_ref_from_event_schema(schema: dict[str, Any], event_name: str) -> str:
    for entry in schema.get("allOf", []):
        properties = entry.get("properties", {}) if isinstance(entry, dict) else {}
        event_type = properties.get("type", {})
        payload = properties.get("payload", {})
        if event_type.get("const") == event_name and "$ref" in payload:
            ref = str(payload["$ref"])
            prefix = "https://ai-hina.local/contracts/v1/"
            if not ref.startswith(prefix):
                raise ValueError(f"payload ref for {event_name} must use the v1 namespace")
            return f"schemas/v1/{ref.removeprefix(prefix)}"
    raise ValueError(f"event schema does not select a payload for {event_name}")


def digest_inputs(contracts: Path) -> str:
    hasher = hashlib.sha256()
    inputs: list[Path] = [
        contracts / "catalog.v1.json",
        contracts / "compatibility-policy.v1.json",
    ]
    inputs.extend(sorted((contracts / "schemas" / "v1").rglob("*.schema.json")))
    for path in inputs:
        hasher.update(path.relative_to(contracts).as_posix().encode("utf-8"))
        hasher.update(b"\0")
        parsed = load_json(path)
        hasher.update(json.dumps(parsed, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode("utf-8"))
        hasher.update(b"\0")
    return hasher.hexdigest()


def render_python(
    catalog: dict[str, Any],
    digest: str,
    events: list[EventProjection],
    schema_files: dict[str, str],
    payload_schema_files: dict[str, str],
    media_schema: dict[str, Any],
    envelope_schema: dict[str, Any],
) -> str:
    event_names = [event.name for event in events]
    event_literal = ", ".join(repr(name) for name in event_names)
    event_tuple = ", ".join(repr(name) for name in event_names)
    if len(event_names) == 1:
        event_tuple += ","
    payload_union = " | ".join(event.payload_type for event in events)
    envelope_union = " | ".join(event.envelope_type for event in events)
    schema_mapping = json.dumps(schema_files, indent=4, sort_keys=True)
    payload_schema_mapping = json.dumps(payload_schema_files, indent=4, sort_keys=True)

    lines = [
        f"# {HEADER}",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, NotRequired, TypedDict",
        "",
        f"CATALOG_VERSION = {catalog['catalogVersion']!r}",
        f"CATALOG_DIGEST = {digest!r}",
        f"MAX_JSON_ENVELOPE_BYTES = {MAX_JSON_ENVELOPE_BYTES}",
        f"MAX_JSON_NESTING_DEPTH = {MAX_JSON_NESTING_DEPTH}",
    ]
    for event in events:
        lines.append(f"{event.const_name} = {event.name!r}")
    lines.extend(
        [
            f"EventType = Literal[{event_literal}]",
            f"EVENT_TYPES: tuple[EventType, ...] = ({event_tuple})",
            f"EVENT_SCHEMA_FILES: dict[EventType, str] = {schema_mapping}",
            f"EVENT_PAYLOAD_SCHEMA_FILES: dict[EventType, str] = {payload_schema_mapping}",
            "",
            "",
        ]
    )
    lines.extend(render_python_typed_dict("MediaReference", media_schema))
    lines.append("")
    for event in events:
        lines.extend(render_python_typed_dict(event.payload_type, event.payload_schema))
        lines.append("")
    lines.extend(render_python_envelope(envelope_schema, payload_union))
    lines.append("")
    for event in events:
        lines.extend(
            [
                f"class {event.envelope_type}(EventEnvelopeV1):",
                f"    type: Literal[{event.name!r}]",
                f"    payload: {event.payload_type}",
                "",
                "",
            ]
        )
    lines.extend(
        [
            f"KnownEventEnvelopeV1 = {envelope_union}",
            "",
            "",
            "class ValidationDiagnostic(TypedDict):",
            "    code: str",
            "    detail: NotRequired[str]",
            "",
        ]
    )
    return "\n".join(lines)


def render_typescript(
    catalog: dict[str, Any],
    digest: str,
    events: list[EventProjection],
    schema_files: dict[str, str],
    payload_schema_files: dict[str, str],
    media_schema: dict[str, Any],
    envelope_schema: dict[str, Any],
) -> str:
    event_names = [event.name for event in events]
    event_union = " | ".join(json.dumps(name) for name in event_names)
    event_array = ", ".join(json.dumps(name) for name in event_names)
    payload_union = " | ".join(event.payload_type for event in events)
    schema_mapping = json.dumps(schema_files, indent=2, sort_keys=True)
    payload_schema_mapping = json.dumps(payload_schema_files, indent=2, sort_keys=True)
    imports = [
        'import eventEnvelopeSchema from "../schemas/v1/event-envelope.schema.json";',
        'import mediaReferenceSchema from "../schemas/v1/media-reference.schema.json";',
    ]
    for event in events:
        imports.append(f'import {event.payload_import_name} from "../{event.payload_schema_path}";')
    for event in events:
        imports.append(f'import {event.event_import_name} from "../{event.event_schema_path}";')

    lines = [
        f"// {HEADER}",
        *imports,
        "",
        f"export const CATALOG_VERSION = {json.dumps(catalog['catalogVersion'])} as const;",
        f"export const CATALOG_DIGEST = {json.dumps(digest)} as const;",
        f"export const MAX_JSON_ENVELOPE_BYTES = {MAX_JSON_ENVELOPE_BYTES} as const;",
        f"export const MAX_JSON_NESTING_DEPTH = {MAX_JSON_NESTING_DEPTH} as const;",
    ]
    for event in events:
        lines.append(f"export const {event.const_name} = {json.dumps(event.name)} as const;")
    lines.extend(
        [
            f"export type EventType = {event_union};",
            f"export const EVENT_TYPES = [{event_array}] as const;",
            f"export const EVENT_SCHEMA_FILES = {schema_mapping} as const;",
            f"export const EVENT_PAYLOAD_SCHEMA_FILES = {payload_schema_mapping} as const;",
            "export const SUPPORT_SCHEMA_MODULES = [",
            "  eventEnvelopeSchema,",
            "  mediaReferenceSchema,",
        ]
    )
    for event in events:
        lines.append(f"  {event.payload_import_name},")
    lines.extend(["] as const;", "export const EVENT_SCHEMA_MODULES = {"])
    for event in events:
        lines.append(f"  {json.dumps(event.name)}: {event.event_import_name},")
    lines.extend(["} as const;", ""])
    lines.extend(render_ts_interface("MediaReference", media_schema))
    lines.append("")
    for event in events:
        lines.extend(render_ts_interface(event.payload_type, event.payload_schema))
        lines.append("")
    lines.extend(render_ts_envelope(envelope_schema, payload_union))
    lines.append("")
    for event in events:
        lines.extend(
            [
                f"export interface {event.envelope_type} extends EventEnvelopeV1 {{",
                f"  type: {json.dumps(event.name)};",
                f"  payload: {event.payload_type};",
                "}",
                "",
            ]
        )
    lines.append(f"export type KnownEventEnvelopeV1 = {' | '.join(event.envelope_type for event in events)};")
    lines.append("")
    return "\n".join(lines)


def render_python_typed_dict(name: str, schema: dict[str, Any]) -> list[str]:
    if schema.get("type") != "object":
        raise ValueError(f"{name} must be an object schema")
    required = set(schema.get("required", []))
    lines = [f"class {name}(TypedDict):"]
    for prop_name, prop_schema in sorted(schema.get("properties", {}).items()):
        suffix = "" if prop_name in required else " | None"
        lines.append(f"    {prop_name}: {python_type(prop_schema)}{suffix}")
    if len(lines) == 1:
        lines.append("    pass")
    return lines


def render_python_envelope(schema: dict[str, Any], payload_type: str) -> list[str]:
    lines = ["class EventEnvelopeV1(TypedDict):"]
    for prop_name, prop_schema in sorted(schema.get("properties", {}).items()):
        if prop_name == "payload":
            prop_type = payload_type
        elif prop_name == "media":
            prop_type = "list[MediaReference]"
        elif prop_name == "type":
            prop_type = "EventType"
        else:
            prop_type = python_type(prop_schema)
        lines.append(f"    {prop_name}: {prop_type}")
    return lines


def render_ts_interface(name: str, schema: dict[str, Any]) -> list[str]:
    if schema.get("type") != "object":
        raise ValueError(f"{name} must be an object schema")
    lines = [f"export interface {name} {{"]
    required = set(schema.get("required", []))
    for prop_name, prop_schema in sorted(schema.get("properties", {}).items()):
        optional = "" if prop_name in required else "?"
        lines.append(f"  {prop_name}{optional}: {ts_type(prop_schema)};")
    lines.append("}")
    return lines


def render_ts_envelope(schema: dict[str, Any], payload_type: str) -> list[str]:
    lines = ["export interface EventEnvelopeV1 {"]
    for prop_name, prop_schema in sorted(schema.get("properties", {}).items()):
        if prop_name == "payload":
            prop_type = payload_type
        elif prop_name == "media":
            prop_type = "MediaReference[]"
        elif prop_name == "type":
            prop_type = "EventType"
        else:
            prop_type = ts_type(prop_schema)
        lines.append(f"  {prop_name}: {prop_type};")
    lines.append("}")
    return lines


def python_type(schema: dict[str, Any]) -> str:
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    if "enum" in schema:
        return "Literal[" + ", ".join(repr(item) for item in sorted(schema["enum"], key=repr)) + "]"
    if "anyOf" in schema:
        return " | ".join(unique_preserve_order(python_type(child) for child in schema["anyOf"]))
    schema_type = schema.get("type")
    if schema_type == "string":
        return "str"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "int | float"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "null":
        return "None"
    if schema_type == "array":
        return f"list[{python_type(schema.get('items', {}))}]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"dict[str, {python_type(additional)}]"
        return "dict[str, Any]"
    if "$ref" in schema:
        ref = str(schema["$ref"])
        if ref.endswith("media-reference.schema.json"):
            return "MediaReference"
    return "Any"


def ts_type(schema: dict[str, Any]) -> str:
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in sorted(schema["enum"], key=repr))
    if "anyOf" in schema:
        return " | ".join(unique_preserve_order(ts_type(child) for child in schema["anyOf"]))
    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"{ts_type(schema.get('items', {}))}[]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional)}>"
        return "Record<string, unknown>"
    if "$ref" in schema:
        ref = str(schema["$ref"])
        if ref.endswith("media-reference.schema.json"):
            return "MediaReference"
    return "unknown"


def unique_preserve_order(values: Any) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


def constant_name(event_name: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", event_name.upper()).strip("_")


def pascal_name(event_name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", event_name) if part)


def camel_name(prefix: str, event_name: str) -> str:
    pascal = pascal_name(event_name)
    return prefix + pascal


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    raise SystemExit(main())
