from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


MAX_JSON_ENVELOPE_BYTES = 1_048_576
HEADER = "Generated by tools/contracts/generate_models.py; do not edit by hand."


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    parser.add_argument("--root", default=".", help="repository root")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    rendered = render_outputs(root)
    changed: list[str] = []
    for relative, content in rendered.items():
        path = root / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            changed.append(relative)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if changed and args.check:
        for relative in changed:
            print(f"E_GEN_DRIFT {relative}", file=sys.stderr)
        return 1
    return 0


def render_outputs(root: Path) -> dict[str, str]:
    contracts = root / "packages" / "contracts"
    catalog = load_json(contracts / "catalog.v1.json")
    policy = load_json(contracts / "compatibility-policy.v1.json")
    event_schemas = {
        event["name"]: load_json(contracts / event["schema"])
        for event in sorted(catalog["events"], key=lambda item: item["name"])
    }
    digest = digest_inputs(contracts, catalog, policy)
    event_names = sorted(event_schemas)
    schema_files = {event["name"]: event["schema"] for event in sorted(catalog["events"], key=lambda item: item["name"])}
    return {
        "packages/contracts/src/hina_contracts/generated.py": render_python(catalog, digest, event_names, schema_files),
        "packages/contracts/src/generated.ts": render_typescript(catalog, digest, event_names, schema_files),
    }


def digest_inputs(contracts: Path, catalog: dict[str, Any], policy: dict[str, Any]) -> str:
    hasher = hashlib.sha256()
    inputs: list[Path] = [
        contracts / "catalog.v1.json",
        contracts / "compatibility-policy.v1.json",
    ]
    inputs.extend(sorted((contracts / "schemas" / "v1").rglob("*.schema.json")))
    for path in inputs:
        hasher.update(path.relative_to(contracts).as_posix().encode("utf-8"))
        hasher.update(b"\0")
        parsed = load_json(path)
        hasher.update(json.dumps(parsed, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode("utf-8"))
        hasher.update(b"\0")
    return hasher.hexdigest()


def render_python(
    catalog: dict[str, Any],
    digest: str,
    event_names: list[str],
    schema_files: dict[str, str],
) -> str:
    event_literal = ", ".join(repr(name) for name in event_names)
    event_tuple = ", ".join(repr(name) for name in event_names)
    if len(event_names) == 1:
        event_tuple += ","
    schema_mapping = json.dumps(schema_files, indent=4, sort_keys=True)
    lines = [
        f"# {HEADER}",
        "from __future__ import annotations",
        "",
        "from typing import Literal, NotRequired, TypedDict",
        "",
        f"CATALOG_VERSION = {catalog['catalogVersion']!r}",
        f"CATALOG_DIGEST = {digest!r}",
        f"MAX_JSON_ENVELOPE_BYTES = {MAX_JSON_ENVELOPE_BYTES}",
        f"HINA_CONTRACT_ECHO_V1 = {event_names[0]!r}",
        f"EventType = Literal[{event_literal}]",
        f"EVENT_TYPES: tuple[EventType, ...] = ({event_tuple})",
        f"EVENT_SCHEMA_FILES: dict[EventType, str] = {schema_mapping}",
        "",
        "",
        "class MediaReference(TypedDict):",
        "    mediaId: str",
        "    kind: Literal['audio', 'binary', 'image', 'video']",
        "    mimeType: str",
        "    byteLength: int",
        "    sha256: str",
        "    transportCorrelationId: str",
        "",
        "",
        "class HinaContractEchoV1Payload(TypedDict):",
        "    message: str",
        "    locale: str",
        "    tags: list[str]",
        "    metadata: dict[str, bool | int | str | None]",
        "",
        "",
        "class EventEnvelopeV1(TypedDict):",
        "    schemaVersion: Literal['1.0']",
        "    eventId: str",
        "    type: EventType",
        "    scope: Literal['global', 'session', 'turn']",
        "    sessionId: str | None",
        "    turnId: str | None",
        "    correlationId: str",
        "    causationId: str | None",
        "    source: str",
        "    trustLevel: Literal['authenticated', 'owner', 'public', 'trusted_local', 'untrusted']",
        "    occurredAt: str",
        "    expiresAt: str | None",
        "    deadline: str | None",
        "    idempotencyKey: str | None",
        "    streamId: str | None",
        "    sequence: int | None",
        "    media: list[MediaReference]",
        "    payload: HinaContractEchoV1Payload",
        "",
        "",
        "class HinaContractEchoV1Envelope(EventEnvelopeV1):",
        "    type: Literal['hina.contract.echo.v1']",
        "    payload: HinaContractEchoV1Payload",
        "",
        "",
        "class ValidationDiagnostic(TypedDict):",
        "    code: str",
        "    detail: NotRequired[str]",
        "",
    ]
    return "\n".join(lines)


def render_typescript(
    catalog: dict[str, Any],
    digest: str,
    event_names: list[str],
    schema_files: dict[str, str],
) -> str:
    event_union = " | ".join(json.dumps(name) for name in event_names)
    event_array = ", ".join(json.dumps(name) for name in event_names)
    schema_mapping = json.dumps(schema_files, indent=2, sort_keys=True)
    lines = [
        f"// {HEADER}",
        f"export const CATALOG_VERSION = {json.dumps(catalog['catalogVersion'])} as const;",
        f"export const CATALOG_DIGEST = {json.dumps(digest)} as const;",
        f"export const MAX_JSON_ENVELOPE_BYTES = {MAX_JSON_ENVELOPE_BYTES} as const;",
        f"export const HINA_CONTRACT_ECHO_V1 = {json.dumps(event_names[0])} as const;",
        f"export type EventType = {event_union};",
        f"export const EVENT_TYPES = [{event_array}] as const;",
        f"export const EVENT_SCHEMA_FILES = {schema_mapping} as const;",
        "",
        "export interface MediaReference {",
        "  mediaId: string;",
        '  kind: "audio" | "binary" | "image" | "video";',
        "  mimeType: string;",
        "  byteLength: number;",
        "  sha256: string;",
        "  transportCorrelationId: string;",
        "}",
        "",
        "export interface HinaContractEchoV1Payload {",
        "  message: string;",
        "  locale: string;",
        "  tags: string[];",
        "  metadata: Record<string, boolean | number | string | null>;",
        "}",
        "",
        "export interface EventEnvelopeV1 {",
        '  schemaVersion: "1.0";',
        "  eventId: string;",
        "  type: EventType;",
        '  scope: "global" | "session" | "turn";',
        "  sessionId: string | null;",
        "  turnId: string | null;",
        "  correlationId: string;",
        "  causationId: string | null;",
        "  source: string;",
        '  trustLevel: "authenticated" | "owner" | "public" | "trusted_local" | "untrusted";',
        "  occurredAt: string;",
        "  expiresAt: string | null;",
        "  deadline: string | null;",
        "  idempotencyKey: string | null;",
        "  streamId: string | null;",
        "  sequence: number | null;",
        "  media: MediaReference[];",
        "  payload: HinaContractEchoV1Payload;",
        "}",
        "",
        "export interface HinaContractEchoV1Envelope extends EventEnvelopeV1 {",
        '  type: "hina.contract.echo.v1";',
        "  payload: HinaContractEchoV1Payload;",
        "}",
        "",
    ]
    return "\n".join(lines)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    raise SystemExit(main())
