# Generated by tools/contracts/generate_models.py; do not edit by hand.
from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict

CATALOG_VERSION = '1.0'
CATALOG_DIGEST = '2aa4b921baad82e292d4d9e42c3e5d2dc42c84ffcd9c9b55f6dbaf0fb6a6ffdf'
MAX_JSON_ENVELOPE_BYTES = 1048576
MAX_JSON_NESTING_DEPTH = 128
HINA_CONTRACT_ECHO_V1 = 'hina.contract.echo.v1'
EventType = Literal['hina.contract.echo.v1']
EVENT_TYPES: tuple[EventType, ...] = ('hina.contract.echo.v1',)
EVENT_SCHEMA_FILES: dict[EventType, str] = {
    "hina.contract.echo.v1": "schemas/v1/events/hina.contract.echo.v1.schema.json"
}
EVENT_PAYLOAD_SCHEMA_FILES: dict[EventType, str] = {
    "hina.contract.echo.v1": "schemas/v1/payloads/hina.contract.echo.v1.payload.schema.json"
}


class MediaReference(TypedDict):
    byteLength: int
    kind: Literal['audio', 'binary', 'image', 'video']
    mediaId: str
    mimeType: str
    sha256: str
    transportCorrelationId: str

class HinaContractEchoV1Payload(TypedDict):
    locale: str
    message: str
    metadata: dict[str, bool | int | None | str]
    tags: list[str]

class EventEnvelopeV1(TypedDict):
    causationId: str | None
    correlationId: str
    deadline: str | None
    eventId: str
    expiresAt: str | None
    idempotencyKey: str | None
    media: list[MediaReference]
    occurredAt: str
    payload: HinaContractEchoV1Payload
    schemaVersion: Literal['1.0']
    scope: Literal['global', 'session', 'turn']
    sequence: int | None
    sessionId: str | None
    source: str
    streamId: str | None
    trustLevel: Literal['authenticated', 'owner', 'public', 'trusted_local', 'untrusted']
    turnId: str | None
    type: EventType

class HinaContractEchoV1Envelope(EventEnvelopeV1):
    type: Literal['hina.contract.echo.v1']
    payload: HinaContractEchoV1Payload


KnownEventEnvelopeV1 = HinaContractEchoV1Envelope


class ValidationDiagnostic(TypedDict):
    code: str
    detail: NotRequired[str]
