# Generated by tools/contracts/generate_models.py; do not edit by hand.
from __future__ import annotations

from typing import Literal, NotRequired, TypedDict

CATALOG_VERSION = '1.0'
CATALOG_DIGEST = '90a642d6906b48fd75da620edb26625164f5b9192b88422c4b94dfad88a6beeb'
MAX_JSON_ENVELOPE_BYTES = 1048576
HINA_CONTRACT_ECHO_V1 = 'hina.contract.echo.v1'
EventType = Literal['hina.contract.echo.v1']
EVENT_TYPES: tuple[EventType, ...] = ('hina.contract.echo.v1',)
EVENT_SCHEMA_FILES: dict[EventType, str] = {
    "hina.contract.echo.v1": "schemas/v1/events/hina.contract.echo.v1.schema.json"
}


class MediaReference(TypedDict):
    mediaId: str
    kind: Literal['audio', 'binary', 'image', 'video']
    mimeType: str
    byteLength: int
    sha256: str
    transportCorrelationId: str


class HinaContractEchoV1Payload(TypedDict):
    message: str
    locale: str
    tags: list[str]
    metadata: dict[str, bool | int | str | None]


class EventEnvelopeV1(TypedDict):
    schemaVersion: Literal['1.0']
    eventId: str
    type: EventType
    scope: Literal['global', 'session', 'turn']
    sessionId: str | None
    turnId: str | None
    correlationId: str
    causationId: str | None
    source: str
    trustLevel: Literal['authenticated', 'owner', 'public', 'trusted_local', 'untrusted']
    occurredAt: str
    expiresAt: str | None
    deadline: str | None
    idempotencyKey: str | None
    streamId: str | None
    sequence: int | None
    media: list[MediaReference]
    payload: HinaContractEchoV1Payload


class HinaContractEchoV1Envelope(EventEnvelopeV1):
    type: Literal['hina.contract.echo.v1']
    payload: HinaContractEchoV1Payload


class ValidationDiagnostic(TypedDict):
    code: str
    detail: NotRequired[str]
